import streamlit as st
from PIL import Image

questName = ["Fishing gear","Tiger safari","Scrap metal","Eagle eye","Humanitatian supplies","The cult - part 1","The cult - part 2","Samples","Tarragroup employee","Spa tour - part 1","Spa tour - part 2","Spa tour - part 3","Spa tpur - part 4","Spa tour - part 5","Spa tour - part 6","Spa tour - part 7","Cargo x - part 1","Cargo x - part 2","Cargo x - part 3","Lend least - part 2","Wet job - part 1","Wet job - part 2","Wet job - part 3","Wet job - part 4","Wet job - part 5","Wet job - part 6","The guide","Peacekeeping mission","Mentor","Classified technologies","Revision","Cleaner","Special equipment","Cargo x - part 4","Counteraction","Overpopulation","Revision - part 2","Road closed","Your car needs a service"]
questInfo = ["Stash an sv-98 and a multi tool at an old boat then extract","Mark 3 tiger vehicles on customs and extract","Mark 3 tanks on shoreline","Find downed uav's and sas drives on shoreline and extract","Mark 2 U.N. cargo trucks, handover 5 mre rations and kill 10 scavs while wearing the U.N. uniform","Find the missing informant on shoreline","Mark all ritual spots on customs, woods and shoreline","Turn in found in raid injectors to peacekeeper","Find sanitars workplace, take his flash drive, extract from the location","Kill 7 scavs with a 12 gauge shotgun with a headshot on shoreline","Mark the helicopter and safe road on shoreline","Hand over wd-40, 2 clin window cleaners, 2 corrigated hoses and 2 bleach to peacekeeper","Locate the generators on shoreline","Handover the sanatorium key","Handover 8000 U.S. dollars","Handover 4 morphines, 2 alkali waters, 2 corrugated hoses and 2 propaine tanks","Find the information in room 306 of the resort and extract","Find the information in room 108 of the resort and extract","Find the hidden cargo in the resorts pool room and extract","Find 2 found in raid virtex processors and 1 found in raid COFDM transmitter","Kill 10 scavs on shoreline with a suppressed m4a1","Marj the fishermans house on shoreline","Find artyoms car on shoreline","Find infor in the health resort and extract","Find artyoms work in room 328 of the health resort and extract","Reach level 7 sniper skill","Survive all maps without dieing","Kill 12 scavs on customs, interchange, shoreline and woods while using the U.N. uniform","Handover 50,000 euros","Obtain the package in the D2 bunker and extract","Mark all the tanks on reserve","Eliminate 50 raiders on reserve","Handover all special equiptment","Locate the terragroup cargo on lighthouse and extract","Kill 20 bear pmc's on lighthouse and handover their dogtags","Secure the cottage area on lighthouse","Mark all tanks on lighthouse","Locate the carog on streets of tarkov, determine the ambush spot and extract","Obtain the storage device from the car dealership and extract"]

st.title("Peacekeeper")

image = Image.open('Peacekeeper_Portrait.webp')
st.image(image)

for i in range(len(questName)):
    st.title(questName[i])
    st.write(questInfo[i])