import streamlit as st
from PIL import Image

questName = ["Debut","Search","Checking","Shootout Picnic","Delivery From The Past","BP depot","The Bunker Part 1","The Bunker Part 2","Bad Rep Evidence","Ice Cream Cones","PostMan Part 1","Shaking Up Teller","The Punisher","The Punisher Part 2","Anesthesia","The Punisher Part 3","The Punisher Part 4","The Punisher Part 5","The Punisher Part 6","Polikhim Hobo","Big Customer","No Offence","Grenadier","Perfect Mediator","Insomnia","Test Drive Part 1","Regulated Materials","Rigged game","Documents","No place for renegades","Capturing Outposts","Intimidator","Escort","Easy Job - Part 1","Easy Job - Part 2","Our Own Land","You've Got Mail","Glory to CPSU","Our Own Land"]
questInfo = ["Eliminate 5 Scavs all over the Tarkov territory and hand over 2 mp-133 shotguns","Find Prapor’s missing convoy, Locate USEC temporary camp  and extract","Find pocket watch on customs then extrace","Kill 15 scavs on Woods","Find a case in Custom's offic, extract, place the case in factory","Mark 4 fuel tanks on customs","Find the underground bunker, locate the control room and extract","Locate all exterences to the bunker and extract","Find and secure the folder on Customs","Hand over 3 60 round 5.45x39 magazines with the found in raid status","Find the letter on a messenger on factory and extract","Find dorm key 203 and extract","kill 15 scavs on Shoreline with and akm","Kill 23 scavs on Shoreline with a suppressed weapon and turn in 7 lower half masks with the status found in raid","Mark 3 trading posts on Shoreline","Kill 25 scavs on customs with an AKS-74U","Kill 10 scavs on Woods with a 12 gauge shotgun, kill 10 pmc's on Shoreline with a baclava and a scav vest, hand over 5 found in raid A-2607 knives","Hand over 1 ak-74ns, 1 m4a1 and 2 pm pistols, then kill 10 pmc's while wearing a paca body armor and a 6b47 helmet","Kill 15 pmc's with an svd on any map excluding factory, hand over 7 usec and bear dogtags","Kill 25 scavs on customs","Mark the chemical transport on customs and survive","Handover 10 m67 hand grenades","Kill 8 pmc's with grenades","Reach level 4 with all traders (requires level 42)","Kill 30 pmc's at night between the time periods of 22:00 and 05:00","Kill 5 pmc's while using an m1a with a hybrid 46 suppresor and a reap-ir thermal scope","Handover 1 tank battery found in raid and 5 ofz shells found in raid","Mark 3 medical containers on Shoreline","Obtain 3 documents on Reserve","Kill 5 raiders on Reserve","Eliminate 12 pmc's on Customs, Woods, and Shoreline at the outpost areas","Eliminate 40 scavs with headshots"," Eliminate 4 pmc's on every map during the day time","Mark the helicopter in the rogue usec camp and extract","Kill 20 scavs or rogues near the helicopter of the rogue used camp","Kill 20 bear pmc's all over the lighthouse territory and hand over their dogtags","Obtain the registered mail on Streets of Tarkov, hand over the letter","Locate the appartment of Prapors friend and extract","Locate the convoy on Streets of Tarkov, determine the ambush spot and extract"]

st.title("Prapor")

image = Image.open('Prapor_Portrait.webp')
st.image(image)

for i in range(len(questName)):
    st.title(questName[i])
    st.write(questInfo[i])